name: costa_trivia_quiz
description: A beginner-friendly football trivia quiz app built with Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_picture.png
    - assets/images/quiz_ui_hero.png
